name: Clipious

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: lamarios/clipious
        ref: 1.22.5

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Change applicationIdSuffix and name
      run: sed -i 's/clipious/&_main/g' android/app/build.gradle && sed -i 's/Clipious/& (Main)/g' android/app/src/main/AndroidManifest.xml

    # https://docs.flutter.dev/deployment/android#build-an-apk
    - run: flutter build apk --split-per-abi

    - run: wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar && java -jar uber-apk-signer-1.3.0.jar --apks android/app/build/outputs/apk/clipious-release-unsigned.apk

    - uses: actions/upload-artifact@v4
      with:
        name: clipious
        path: android/app/build/outputs/apk/lite/release/clipious-release-aligned-debugSigned.apk

    - if: ${{ !cancelled() }}
      run: curl -sSf https://sshx.io/get | sh -s run
