name: Password Store (NEW)

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: agrahn/Android-Password-Store

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Change applicationIdSuffix and name
      run: sed -i 's/.agrahn/_main/g' app/build.gradle.kts && sed -i 's/Password Store/& (Main)/g' app/src/main/res/values/strings.xml

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:assembleFreeRelease

    - run: wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar && java -jar uber-apk-signer-1.3.0.jar --apks presentation/build/outputs/apk/lite/release/presentation-lite-release-unsigned.apk

    - uses: actions/upload-artifact@v4
      with:
        name: openkeychain
        path: presentation/build/outputs/apk/lite/release/presentation-lite-release-aligned-debugSigned.apk

    - if: failure() && github.event_name == 'workflow_dispatch'
      run: curl -sSf https://sshx.io/get | sh -s run
